# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  port: 8080
  secret_key: "f06022ee51f19c305926fb2557df6adb410ec8c21ae88c9dfd264614e90d5660"
  limiter: false
  image_proxy: true
redis:
  url: redis://redis:6379/0
